# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import envoie_pb2 as envoie__pb2


class EnvoieServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEnvoie = channel.unary_unary(
                '/envoie.EnvoieService/GetEnvoie',
                request_serializer=envoie__pb2.GetEnvoieRequest.SerializeToString,
                response_deserializer=envoie__pb2.Envoie.FromString,
                )


class EnvoieServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEnvoie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvoieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEnvoie': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvoie,
                    request_deserializer=envoie__pb2.GetEnvoieRequest.FromString,
                    response_serializer=envoie__pb2.Envoie.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'envoie.EnvoieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnvoieService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEnvoie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/envoie.EnvoieService/GetEnvoie',
            envoie__pb2.GetEnvoieRequest.SerializeToString,
            envoie__pb2.Envoie.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
