# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoie.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoie.proto',
  package='envoie',
  syntax='proto3',
  serialized_options=b'\n\027io.grpc.examples.envoieB\013EnvoieProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x65nvoie.proto\x12\x06\x65nvoie\"\xa0\x01\n\x06\x45nvoie\x12\x12\n\nnomReunion\x18\x01 \x01(\t\x12\x14\n\x0cmailEtudiant\x18\x02 \x01(\t\x12\x12\n\nteteOuMain\x18\x03 \x01(\t\x12\x13\n\x0b\x65tatReunion\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\t\n\x01x\x18\x06 \x01(\x02\x12\t\n\x01y\x18\x07 \x01(\x02\x12\t\n\x01z\x18\x08 \x01(\x02\x12\x13\n\x0btentaConnec\x18\t \x01(\t\"\xaa\x01\n\x10GetEnvoieRequest\x12\x12\n\nnomReunion\x18\x01 \x01(\t\x12\x14\n\x0cmailEtudiant\x18\x02 \x01(\t\x12\x12\n\nteteOuMain\x18\x03 \x01(\t\x12\x13\n\x0b\x65tatReunion\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\t\n\x01x\x18\x06 \x01(\x02\x12\t\n\x01y\x18\x07 \x01(\x02\x12\t\n\x01z\x18\x08 \x01(\x02\x12\x13\n\x0btentaConnec\x18\t \x01(\t2F\n\rEnvoieService\x12\x35\n\tGetEnvoie\x12\x18.envoie.GetEnvoieRequest\x1a\x0e.envoie.EnvoieB(\n\x17io.grpc.examples.envoieB\x0b\x45nvoieProtoP\x01\x62\x06proto3'
)




_ENVOIE = _descriptor.Descriptor(
  name='Envoie',
  full_name='envoie.Envoie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nomReunion', full_name='envoie.Envoie.nomReunion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mailEtudiant', full_name='envoie.Envoie.mailEtudiant', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='teteOuMain', full_name='envoie.Envoie.teteOuMain', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='etatReunion', full_name='envoie.Envoie.etatReunion', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='envoie.Envoie.image', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='envoie.Envoie.x', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='envoie.Envoie.y', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='envoie.Envoie.z', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tentaConnec', full_name='envoie.Envoie.tentaConnec', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=185,
)


_GETENVOIEREQUEST = _descriptor.Descriptor(
  name='GetEnvoieRequest',
  full_name='envoie.GetEnvoieRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nomReunion', full_name='envoie.GetEnvoieRequest.nomReunion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mailEtudiant', full_name='envoie.GetEnvoieRequest.mailEtudiant', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='teteOuMain', full_name='envoie.GetEnvoieRequest.teteOuMain', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='etatReunion', full_name='envoie.GetEnvoieRequest.etatReunion', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='envoie.GetEnvoieRequest.image', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='envoie.GetEnvoieRequest.x', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='envoie.GetEnvoieRequest.y', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='envoie.GetEnvoieRequest.z', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tentaConnec', full_name='envoie.GetEnvoieRequest.tentaConnec', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=358,
)

DESCRIPTOR.message_types_by_name['Envoie'] = _ENVOIE
DESCRIPTOR.message_types_by_name['GetEnvoieRequest'] = _GETENVOIEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Envoie = _reflection.GeneratedProtocolMessageType('Envoie', (_message.Message,), {
  'DESCRIPTOR' : _ENVOIE,
  '__module__' : 'envoie_pb2'
  # @@protoc_insertion_point(class_scope:envoie.Envoie)
  })
_sym_db.RegisterMessage(Envoie)

GetEnvoieRequest = _reflection.GeneratedProtocolMessageType('GetEnvoieRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETENVOIEREQUEST,
  '__module__' : 'envoie_pb2'
  # @@protoc_insertion_point(class_scope:envoie.GetEnvoieRequest)
  })
_sym_db.RegisterMessage(GetEnvoieRequest)


DESCRIPTOR._options = None

_ENVOIESERVICE = _descriptor.ServiceDescriptor(
  name='EnvoieService',
  full_name='envoie.EnvoieService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=360,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEnvoie',
    full_name='envoie.EnvoieService.GetEnvoie',
    index=0,
    containing_service=None,
    input_type=_GETENVOIEREQUEST,
    output_type=_ENVOIE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENVOIESERVICE)

DESCRIPTOR.services_by_name['EnvoieService'] = _ENVOIESERVICE

# @@protoc_insertion_point(module_scope)
